In [1]:
import pandas as pd
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from IPython.display import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import f_classif

In [2]:
customer = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/customers_dataset.csv')
geo = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/geolocation_dataset.csv')
orderitem = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/order_items_dataset.csv')
orderpay = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/order_payments_dataset.csv')
orderreview = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/order_reviews_dataset.csv')
orders= pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/orders_dataset.csv')
product = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/products_dataset.csv')
seller = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/sellers_dataset.csv')
catetranslation = pd.read_csv('C:/Users/hp/Downloads/E-Com Simple Data/product_category_name_translation.csv')

In [3]:
print('customer' ,customer.shape)

print('geo',geo.shape)

print('orderitem' ,orderitem.shape)

print('orderpay',orderpay.shape)

print('orderreview' ,orderreview.shape)

print('orders' ,orders.shape)

print('product' ,product.shape)

print('seller' ,seller.shape)

print('catetranslation', catetranslation.shape)

customer (99441, 5)
geo (1000163, 5)
orderitem (112650, 7)
orderpay (103886, 5)
orderreview (99224, 7)
orders (99441, 8)
product (32951, 9)
seller (3095, 4)
catetranslation (71, 2)

In [4]:
dataset = [customer , geo ,orderitem, orderpay , orders , orderreview ,seller , product, catetranslation ]
titles = ["customers","geolocations","items","payments", "orders","reviews" ,"sellers","products","product_cat_translation"]
info_dataset = pd.DataFrame({},)
info_dataset['dataset']= titles

info_dataset = pd.DataFrame({},)
info_dataset['dataset']= titles

info_dataset['no_of_columns']= [len(df.columns) for df in dataset ]
info_dataset['columns_name']= [', '.join(list(df.columns)) for df in dataset] 
info_dataset['no_of_rows'] = [len(df) for df in dataset]
info_dataset.style.background_gradient(cmap ='Greys')

In [5]:
df= pd.merge(customer, orders, on="customer_id")
df= pd.merge(df, orderreview, on="order_id")
df= pd.merge(df, orderitem, on="order_id")
df= pd.merge(df, product, on="product_id")
df= pd.merge(df, orderpay, on="order_id")
df= pd.merge(df, seller, on='seller_id')
df= pd.merge(df, catetranslation, on='product_category_name')
df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,64.0,31.0,1,credit_card,2,146.87,8577,itaquaquecetuba,SP,office_furniture
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,64.0,31.0,1,credit_card,1,275.79,8577,itaquaquecetuba,SP,office_furniture
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,64.0,31.0,1,credit_card,1,275.79,8577,itaquaquecetuba,SP,office_furniture
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,64.0,31.0,1,credit_card,7,140.61,8577,itaquaquecetuba,SP,office_furniture
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,64.0,31.0,1,credit_card,10,137.58,8577,itaquaquecetuba,SP,office_furniture
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115604,e548277911829ffe81aac2b4407de701,a0abd26659c9914690cbd3320d39fd96,92412,canoas,RS,a5f8439f1e560659a492608e370ecde2,delivered,2017-05-27 14:03:20,2017-05-27 14:15:16,2017-05-29 09:30:43,...,15.0,55.0,1,credit_card,10,232.19,89701,concordia,SC,la_cuisine
115605,0fbd856ba1d4961786fb54bd448eb7fe,96328ac15f58fbb232fe14b182103382,89675,vargem bonita,SC,937592924b66482b823ee7ecd185d0ff,delivered,2018-03-31 19:17:43,2018-03-31 19:55:18,2018-04-02 19:10:46,...,21.0,43.0,1,credit_card,8,426.70,89701,concordia,SC,la_cuisine
115606,aa0533eb31ed3be79086f11bb2bec430,a490d5875edefe9bb8f5101ec2f6b56f,13870,sao joao da boa vista,SP,e22a3e8048469ea68906f666d446c25c,delivered,2017-08-28 09:48:01,2017-08-28 10:05:04,2017-08-29 11:05:28,...,12.0,15.0,1,credit_card,3,160.46,89701,concordia,SC,la_cuisine
115607,d11524bb77c28efad04e4467eac8a660,6968d41eb700f1ea39424e04b854bf7e,30130,belo horizonte,MG,1ce0acf125f1bcd636276dd213363196,delivered,2017-07-31 18:10:29,2017-07-31 18:25:20,2017-08-02 18:22:30,...,7.0,40.0,1,credit_card,2,55.18,89701,concordia,SC,la_cuisine
115608,d11524bb77c28efad04e4467eac8a660,6968d41eb700f1ea39424e04b854bf7e,30130,belo horizonte,MG,1ce0acf125f1bcd636276dd213363196,delivered,2017-07-31 18:10:29,2017-07-31 18:25:20,2017-08-02 18:22:30,...,7.0,40.0,2,voucher,1,100.00,89701,concordia,SC,la_cuisine

In [6]:
print(customer.isnull().sum())

print(geo.isnull().sum())

print(orderitem.isnull().sum())

print(orderpay.isnull().sum())

print(orderreview.isnull().sum())

print(orders.isnull().sum())

print(product.isnull().sum())

print(seller.isnull().sum())

print( catetranslation.isnull().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
product_category_name            0
product_category_name_english    0
dtype: int64

In [7]:
print(customer.isna().sum())

print(geo.isna().sum())

print(orderitem.isna().sum())

print(orderpay.isna().sum())

print(orderreview.isna().sum())

print(orders.isna().sum())

print(product.isna().sum())

print(seller.isna().sum())

print( catetranslation.isna().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
product_category_name            0
product_category_name_english    0
dtype: int64

In [8]:
df.dropna(subset=['order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm'], inplace= True)

In [9]:
df.shape

(113193, 40)

In [10]:
print(df.isna().sum())

customer_id                          0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
order_id                             0
order_status                         0
order_purchase_timestamp             0
order_approved_at                    0
order_delivered_carrier_date         0
order_delivered_customer_date        0
order_estimated_delivery_date        0
review_id                            0
review_score                         0
review_comment_title             99700
review_comment_message           65834
review_creation_date                 0
review_answer_timestamp              0
order_item_id                        0
product_id                           0
seller_id                            0
shipping_limit_date                  0
price                                0
freight_value                        0
product_category_name                0
product_name_lenght                  0
product_description_lenght           0
product_photos_qty                   0
product_weight_g                     0
product_length_cm                    0
product_height_cm                    0
product_width_cm                     0
payment_sequential                   0
payment_type                         0
payment_installments                 0
payment_value                        0
seller_zip_code_prefix               0
seller_city                          0
seller_state                         0
product_category_name_english        0
dtype: int64

In [11]:
translation_dict = dict(zip(df['product_category_name'], df['product_category_name_english']))

df['product_category_name'] = df['product_category_name'].map(translation_dict)

In [12]:
df['product_category_name']

0         office_furniture
1         office_furniture
2         office_furniture
3         office_furniture
4         office_furniture
                ...
115604          la_cuisine
115605          la_cuisine
115606          la_cuisine
115607          la_cuisine
115608          la_cuisine
Name: product_category_name, Length: 113193, dtype: object

In [13]:
df = df.drop('product_category_name_english', axis=1)

In [14]:
df.shape

(113193, 39)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from matplotlib import pyplot

label_encoder = LabelEncoder()

# Encode each column of strings separately
df['customer_id'] = label_encoder.fit_transform(df['customer_id'])
df['customer_unique_id'] = label_encoder.fit_transform(df['customer_unique_id'])
df['customer_city'] = label_encoder.fit_transform(df['customer_city'])
df['customer_state'] = label_encoder.fit_transform(df['customer_state'])
df['order_id'] = label_encoder.fit_transform(df['order_id'])
df['order_status'] = label_encoder.fit_transform(df['order_status'])
df['review_id'] = label_encoder.fit_transform(df['review_id'])
df['product_id'] = label_encoder.fit_transform(df['product_id'])
df['seller_id'] = label_encoder.fit_transform(df['seller_id'])
df['product_category_name'] = label_encoder.fit_transform(df['product_category_name'])
df['payment_type'] = label_encoder.fit_transform(df['payment_type'])
df['seller_city'] = label_encoder.fit_transform(df['seller_city'])
df['seller_state'] = label_encoder.fit_transform(df['seller_state'])

In [16]:
df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,product_length_cm,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,seller_zip_code_prefix,seller_city,seller_state
0,2494,47953,14409,1368,25,320,1,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,54.0,64.0,31.0,1,1,2,146.87,8577,249,21
1,50508,56764,68030,3330,13,71523,1,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,54.0,64.0,31.0,1,1,1,275.79,8577,249,21
2,50508,56764,68030,3330,13,71523,1,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,54.0,64.0,31.0,1,1,1,275.79,8577,249,21
3,88975,21673,92480,2506,22,65418,1,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,54.0,64.0,31.0,1,1,7,140.61,8577,249,21
4,39630,12663,25931,2143,18,16995,1,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,54.0,64.0,31.0,1,1,10,137.58,8577,249,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115604,84775,57446,92412,763,22,60983,1,2017-05-27 14:03:20,2017-05-27 14:15:16,2017-05-29 09:30:43,...,55.0,15.0,55.0,1,1,10,232.19,89701,137,19
115605,5770,53650,89675,3963,23,54101,1,2018-03-31 19:17:43,2018-03-31 19:55:18,2018-04-02 19:10:46,...,83.0,21.0,43.0,1,1,8,426.70,89701,137,19
115606,62843,58863,13870,3444,25,83666,1,2017-08-28 09:48:01,2017-08-28 10:05:04,2017-08-29 11:05:28,...,84.0,12.0,15.0,1,1,3,160.46,89701,137,19
115607,77418,37760,30130,448,10,10669,1,2017-07-31 18:10:29,2017-07-31 18:25:20,2017-08-02 18:22:30,...,85.0,7.0,40.0,1,1,2,55.18,89701,137,19
115608,77418,37760,30130,448,10,10669,1,2017-07-31 18:10:29,2017-07-31 18:25:20,2017-08-02 18:22:30,...,85.0,7.0,40.0,2,3,1,100.00,89701,137,19

In [17]:
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])
df['order_delivered_carrier_date'] = pd.to_datetime(df['order_delivered_carrier_date'])
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['review_answer_timestamp'] = pd.to_datetime(df['review_answer_timestamp'])
df['shipping_limit_date']= pd.to_datetime(df['shipping_limit_date'])

In [18]:
df.dtypes

customer_id                               int32
customer_unique_id                        int32
customer_zip_code_prefix                  int64
customer_city                             int32
customer_state                            int32
order_id                                  int32
order_status                              int32
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
review_id                                 int32
review_score                              int64
review_comment_title                     object
review_comment_message                   object
review_creation_date                     object
review_answer_timestamp          datetime64[ns]
order_item_id                             int64
product_id                                int32
seller_id                                 int32
shipping_limit_date              datetime64[ns]
price                                   float64
freight_value                           float64
product_category_name                     int32
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
payment_sequential                        int64
payment_type                              int32
payment_installments                      int64
payment_value                           float64
seller_zip_code_prefix                    int64
seller_city                               int32
seller_state                              int32
dtype: object

In [19]:
df = df.drop(['order_approved_at','order_estimated_delivery_date','order_delivered_customer_date','order_delivered_carrier_date','order_purchase_timestamp','review_answer_timestamp','shipping_limit_date','review_comment_title','review_comment_message','review_creation_date'], axis=1)

In [20]:
df.dtypes

customer_id                     int32
customer_unique_id              int32
customer_zip_code_prefix        int64
customer_city                   int32
customer_state                  int32
order_id                        int32
order_status                    int32
review_id                       int32
review_score                    int64
order_item_id                   int64
product_id                      int32
seller_id                       int32
price                         float64
freight_value                 float64
product_category_name           int32
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
payment_sequential              int64
payment_type                    int32
payment_installments            int64
payment_value                 float64
seller_zip_code_prefix          int64
seller_city                     int32
seller_state                    int32
dtype: object

In [21]:
y = df['review_score']

X = df.drop(columns=['review_score'])

In [22]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.4, random_state=0)
X_test.shape

(45278, 28)

In [43]:
selector = SelectKBest(chi2, k=18)
selector.fit(X_train, y_train)

selected_feature_indices = selector.get_support(indices=True)

selected_feature_names = X_train.columns[selected_feature_indices]
print(selected_feature_names)

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'order_id', 'review_id', 'order_item_id', 'product_id',
       'seller_id', 'price', 'freight_value', 'product_category_name',
       'product_description_lenght', 'product_weight_g',
       'payment_installments', 'payment_value', 'seller_zip_code_prefix',
       'seller_city'],
      dtype='object')

In [24]:
# Mutual Information : utilisée pour évaluer la relation entre chaque caractéristique et la variable cible.
# Elle mesure la quantité d'information que chaque caractéristique fournit sur la variable cible.

from sklearn.feature_selection import mutual_info_classif

mutual_info= mutual_info_classif(X_train, y_train)
mutual_info = pd.Series (mutual_info)
mutual_info.index = X_train.columns
mutual_info.sort_values(ascending=False)

customer_unique_id            0.103441
review_id                     0.103233
customer_id                   0.099891
order_id                      0.097425
payment_value                 0.078301
customer_zip_code_prefix      0.077055
product_id                    0.072308
seller_id                     0.037890
freight_value                 0.035468
seller_zip_code_prefix        0.033569
price                         0.028278
product_description_lenght    0.026430
customer_city                 0.023572
order_item_id                 0.016398
seller_city                   0.016230
product_weight_g              0.012680
order_status                  0.008675
product_category_name         0.008095
customer_state                0.008038
seller_state                  0.003826
product_width_cm              0.003506
payment_type                  0.003370
payment_sequential            0.003072
payment_installments          0.002556
product_height_cm             0.001176
product_length_cm             0.001126
product_photos_qty            0.000012
product_name_lenght           0.000000
dtype: float64

In [42]:
# SelectPercentile : est une approche de sélection de caractéristiques permet de sélectionner un pourcentage spécifique
# des caractéristiques les plus importantes en fonction d'un test statistique.
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import f_regression

selector2 = SelectPercentile(f_regression, percentile=60)

selector2.fit(X, y)

selected_feature_indices2 = selector2.get_support(indices=True)

selected_feature_names2 = X.columns[selected_feature_indices2]

print(selected_feature_names2)

Index(['customer_zip_code_prefix', 'customer_state', 'order_item_id',
       'seller_id', 'freight_value', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'payment_installments',
       'payment_value', 'seller_zip_code_prefix', 'seller_state'],
      dtype='object')

In [41]:
# SelectKBest: est une methode de sélection de caractéristiques qui permet de sélectionner les K meilleures caractéristiques
# en fonction d'un test statistique 
selector3 = SelectKBest(f_classif, k=15)
selector3.fit(X, y)

selected_feature_indices = selector3.get_support(indices=True)

selected_feature_names = X.columns[selected_feature_indices]

print(selected_feature_names)

Index(['customer_zip_code_prefix', 'customer_state', 'order_item_id',
       'freight_value', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'payment_installments',
       'payment_value', 'seller_zip_code_prefix', 'seller_state'],
      dtype='object')