In [30]:
import pandas as pd
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [31]:
df = pd.read_csv('../data/train_merge.csv')
df

,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination,most_frequent_action,most_frequent_action_type,most_frequent_action_detail,most_frequent_device_type,most_frequent_secs_elapsed
0,2014-01-01,2014-01-01,2014-01-04,MALE,62,basic,0,en,sem-non-brand,google,omg,Web,Windows Desktop,Chrome,other,show,data,wishlist_content_update,Windows Desktop,2.0
1,2014-01-01,2014-01-01,2014-01-07,FEMALE,32,facebook,0,en,seo,google,linked,Web,iPad,Mobile Safari,US,ask_question,message_post,contact_host,iPad Tablet,0.0
2,2014-01-01,2014-01-01,2014-12-04,-unknown-,19,basic,0,en,sem-brand,google,untracked,Web,Mac Desktop,Safari,other,personalize,data,wishlist_content_update,Mac Desktop,37.0
3,2014-01-01,2014-01-01,2014-01-01,MALE,25,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF,show,click,wishlist_content_update,Mac Desktop,149.0
4,2014-01-01,2014-01-01,2014-01-02,FEMALE,32,facebook,0,en,direct,direct,untracked,Web,iPad,Mobile Safari,US,ask_question,submit,-unknown-,iPhone,387.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40790,2014-06-30,2014-06-30,2014-08-13,FEMALE,34,basic,0,en,direct,direct,linked,Web,Mac Desktop,Chrome,ES,search_results,view,view_search_results,Mac Desktop,1.0
40791,2014-06-30,2014-06-30,2014-07-13,FEMALE,36,basic,0,en,sem-brand,google,linked,Web,Mac Desktop,Safari,US,show,view,view_search_results,Mac Desktop,78.0
40792,2014-06-30,2014-06-30,2014-07-02,FEMALE,23,basic,0,en,sem-brand,google,omg,Web,Windows Desktop,IE,US,search_results,data,view_search_results,Windows Desktop,29.0
40793,2014-06-30,2014-06-30,2014-06-30,MALE,32,basic,0,en,sem-brand,google,omg,Web,Mac Desktop,Safari,NDF,search_results,view,-unknown-,Mac Desktop,584.0
40794,2014-06-30,2014-06-30,2014-06-30,-unknown-,32,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,NDF,show,view,p3,Mac Desktop,39.0

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df['gender'] = label_encoder.fit_transform(df['gender'])
df['signup_method'] = label_encoder.fit_transform(df['signup_method'])
df['language'] = label_encoder.fit_transform(df['language'])
df['affiliate_channel'] = label_encoder.fit_transform(df['affiliate_channel'])
df['affiliate_provider'] = label_encoder.fit_transform(df['affiliate_provider'])
df['signup_app'] = label_encoder.fit_transform(df['signup_app'])
df['first_affiliate_tracked'] = label_encoder.fit_transform(df['first_affiliate_tracked'])
df['first_device_type'] = label_encoder.fit_transform(df['first_device_type'])
df['first_browser'] = label_encoder.fit_transform(df['first_browser'])
df['most_frequent_action'] = label_encoder.fit_transform(df['most_frequent_action'])
df['country_destination'] = label_encoder.fit_transform(df['country_destination'])
df['most_frequent_action'] = label_encoder.fit_transform(df['most_frequent_action'])
df['most_frequent_action_type'] = label_encoder.fit_transform(df['most_frequent_action_type'])
df['most_frequent_action_detail'] = label_encoder.fit_transform(df['most_frequent_action_detail'])
df['most_frequent_device_type'] = label_encoder.fit_transform(df['most_frequent_device_type'])

df

,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination,most_frequent_action,most_frequent_action_type,most_frequent_action_detail,most_frequent_device_type,most_frequent_secs_elapsed
0,2014-01-01,2014-01-01,2014-01-04,2,62,0,0,5,6,7,3,2,6,6,11,114,3,75,8,2.0
1,2014-01-01,2014-01-01,2014-01-07,1,32,1,0,5,7,7,0,2,7,17,10,22,4,14,10,0.0
2,2014-01-01,2014-01-01,2014-12-04,0,19,0,0,5,5,7,6,2,3,23,11,87,3,75,6,37.0
3,2014-01-01,2014-01-01,2014-01-01,2,25,0,0,5,2,3,6,2,3,6,7,114,2,75,6,149.0
4,2014-01-01,2014-01-01,2014-01-02,1,32,1,0,5,2,3,6,2,7,17,10,22,6,0,11,387.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40790,2014-06-30,2014-06-30,2014-08-13,1,34,0,0,5,2,3,0,2,3,6,3,110,7,73,6,1.0
40791,2014-06-30,2014-06-30,2014-07-13,1,36,0,0,5,5,7,0,2,3,23,10,114,7,73,6,78.0
40792,2014-06-30,2014-06-30,2014-07-02,1,23,0,0,5,5,7,3,2,6,11,10,110,3,73,8,29.0
40793,2014-06-30,2014-06-30,2014-06-30,2,32,0,0,5,5,7,3,2,3,23,7,110,7,0,6,584.0
40794,2014-06-30,2014-06-30,2014-06-30,0,32,0,0,5,2,3,6,2,3,10,7,114,7,43,6,39.0

In [33]:
df= df.drop(columns=['date_account_created','timestamp_first_active','date_first_booking'],axis=1)
df

,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination,most_frequent_action,most_frequent_action_type,most_frequent_action_detail,most_frequent_device_type,most_frequent_secs_elapsed
0,2,62,0,0,5,6,7,3,2,6,6,11,114,3,75,8,2.0
1,1,32,1,0,5,7,7,0,2,7,17,10,22,4,14,10,0.0
2,0,19,0,0,5,5,7,6,2,3,23,11,87,3,75,6,37.0
3,2,25,0,0,5,2,3,6,2,3,6,7,114,2,75,6,149.0
4,1,32,1,0,5,2,3,6,2,7,17,10,22,6,0,11,387.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40790,1,34,0,0,5,2,3,0,2,3,6,3,110,7,73,6,1.0
40791,1,36,0,0,5,5,7,0,2,3,23,10,114,7,73,6,78.0
40792,1,23,0,0,5,5,7,3,2,6,11,10,110,3,73,8,29.0
40793,2,32,0,0,5,5,7,3,2,3,23,7,110,7,0,6,584.0
40794,0,32,0,0,5,2,3,6,2,3,10,7,114,7,43,6,39.0

In [34]:
y

array([11, 10, 11,  7, 10, 11,  7,  4, 10,  7,  7,  7,  7, 10,  7,  7, 10,
       10,  7,  7, 10, 10, 10,  7,  7,  7, 10, 11,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7, 11,  7,  7, 11,  5,  7,  7, 10, 10, 10,  7, 11, 10,
        7,  7,  6,  7,  7,  7,  6, 10, 10,  7,  7,  7,  7,  7,  7,  7, 10,
       10,  7,  7, 10,  7, 11,  7, 10, 10,  7, 10, 10,  7, 11,  0,  5, 11,
       10,  7,  0, 10, 10,  7, 10,  7, 10,  1, 10, 10, 10,  6, 10,  7,  7,
        7, 11,  7,  7, 10,  7,  7, 10, 10,  6,  7, 10,  7,  4,  4,  7,  7,
        7, 10, 11, 10, 10, 10, 11,  7,  7, 10,  7,  7,  7,  7,  7, 10, 10,
       10,  7, 10,  7,  7,  7, 10,  7,  7,  7,  7, 11,  7,  7, 10,  4, 10,
        7,  7,  7, 10, 10,  7,  7,  7,  7,  7, 11, 10,  7, 10,  7, 10, 11,
        7, 10, 10,  4, 10, 10, 10, 10,  1,  7, 10,  4,  7,  7, 10, 10,  7,
       10, 10,  7,  4,  7, 10, 11, 10, 10,  3, 10, 10,  7])

In [35]:
X

array([[ 2., 62.,  0., ..., 75.,  8.,  2.],
       [ 1., 32.,  1., ..., 14., 10.,  0.],
       [ 0., 19.,  0., ..., 75.,  6., 37.],
       ...,
       [ 1., 28.,  0., ...,  0.,  6., 28.],
       [ 0., 45.,  0., ...,  0.,  8.,  3.],
       [ 2., 41.,  1., ...,  0.,  6., 12.]])

In [36]:
y = df['country_destination']
y = y.values[:200]

X = df.drop(columns=['country_destination'])
X = X.values[:200]

In [37]:
y

array([11, 10, 11,  7, 10, 11,  7,  4, 10,  7,  7,  7,  7, 10,  7,  7, 10,
       10,  7,  7, 10, 10, 10,  7,  7,  7, 10, 11,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7, 11,  7,  7, 11,  5,  7,  7, 10, 10, 10,  7, 11, 10,
        7,  7,  6,  7,  7,  7,  6, 10, 10,  7,  7,  7,  7,  7,  7,  7, 10,
       10,  7,  7, 10,  7, 11,  7, 10, 10,  7, 10, 10,  7, 11,  0,  5, 11,
       10,  7,  0, 10, 10,  7, 10,  7, 10,  1, 10, 10, 10,  6, 10,  7,  7,
        7, 11,  7,  7, 10,  7,  7, 10, 10,  6,  7, 10,  7,  4,  4,  7,  7,
        7, 10, 11, 10, 10, 10, 11,  7,  7, 10,  7,  7,  7,  7,  7, 10, 10,
       10,  7, 10,  7,  7,  7, 10,  7,  7,  7,  7, 11,  7,  7, 10,  4, 10,
        7,  7,  7, 10, 10,  7,  7,  7,  7,  7, 11, 10,  7, 10,  7, 10, 11,
        7, 10, 10,  4, 10, 10, 10, 10,  1,  7, 10,  4,  7,  7, 10, 10,  7,
       10, 10,  7,  4,  7, 10, 11, 10, 10,  3, 10, 10,  7])

In [38]:
X

array([[ 2., 62.,  0., ..., 75.,  8.,  2.],
       [ 1., 32.,  1., ..., 14., 10.,  0.],
       [ 0., 19.,  0., ..., 75.,  6., 37.],
       ...,
       [ 1., 28.,  0., ...,  0.,  6., 28.],
       [ 0., 45.,  0., ...,  0.,  8.,  3.],
       [ 2., 41.,  1., ...,  0.,  6., 12.]])

In [39]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.3, random_state=42)

In [40]:
y_train

array([11, 10,  7,  7,  7,  7,  5,  7,  7, 10,  7,  7,  7, 11,  7, 10, 10,
        7,  7,  6, 11,  7, 10, 10,  7, 10,  7,  7,  4,  7, 10,  7,  7,  7,
        7, 10,  7,  7, 11, 10, 10,  7, 10,  7, 10,  7,  7,  7,  7,  7, 10,
       11, 10,  7,  7, 10,  7,  7, 11,  7,  7,  7,  7, 10,  7,  7, 10, 11,
       11,  7, 10, 10,  1,  7,  7, 10,  7,  7,  6,  7, 10,  1, 10, 11,  7,
        7,  4, 10, 10,  5, 10,  4, 10, 10, 10, 10, 10,  7, 10,  7, 10, 10,
        7,  7,  7,  7,  7, 10,  3, 10,  7, 10, 10,  6,  7, 10,  7,  7, 10,
       11, 10,  7,  7,  7,  4, 11, 10,  4,  0,  7, 11,  7, 10, 10, 10, 10,
        7,  7,  7,  7])

In [41]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [42]:
# Initialize XGBClassifier
model = XGBClassifier(
    objective='multi:softmax', 
    num_class=12,               
    n_jobs=-1 
)

param_grid = {
    'max_depth': [3, 6, 9],
    'learning_rate': [0.01, 0.1, 0.2],
    'n_estimators': [100, 200, 300],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring='accuracy',  
    cv=3  
)

In [43]:
X_train

array([[2.00e+00, 7.30e+01, 0.00e+00, ..., 0.00e+00, 0.00e+00, 1.00e+01],
       [2.00e+00, 2.50e+01, 0.00e+00, ..., 1.90e+01, 6.00e+00, 4.51e+03],
       [2.00e+00, 2.50e+01, 1.00e+00, ..., 7.30e+01, 6.00e+00, 3.85e+02],
       ...,
       [2.00e+00, 8.40e+01, 1.00e+00, ..., 0.00e+00, 8.00e+00, 7.30e+01],
       [0.00e+00, 8.90e+01, 0.00e+00, ..., 0.00e+00, 6.00e+00, 2.00e+00],
       [2.00e+00, 2.30e+01, 0.00e+00, ..., 7.50e+01, 8.00e+00, 1.00e+00]])

In [44]:
y_train

array([11, 10,  7,  7,  7,  7,  5,  7,  7, 10,  7,  7,  7, 11,  7, 10, 10,
        7,  7,  6, 11,  7, 10, 10,  7, 10,  7,  7,  4,  7, 10,  7,  7,  7,
        7, 10,  7,  7, 11, 10, 10,  7, 10,  7, 10,  7,  7,  7,  7,  7, 10,
       11, 10,  7,  7, 10,  7,  7, 11,  7,  7,  7,  7, 10,  7,  7, 10, 11,
       11,  7, 10, 10,  1,  7,  7, 10,  7,  7,  6,  7, 10,  1, 10, 11,  7,
        7,  4, 10, 10,  5, 10,  4, 10, 10, 10, 10, 10,  7, 10,  7, 10, 10,
        7,  7,  7,  7,  7, 10,  3, 10,  7, 10, 10,  6,  7, 10,  7,  7, 10,
       11, 10,  7,  7,  7,  4, 11, 10,  4,  0,  7, 11,  7, 10, 10, 10, 10,
        7,  7,  7,  7])

In [45]:
grid_search.fit(X_train, y_train)

C:\Users\ayoub\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

ValueError:
All the 324 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
108 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ayoub\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\core.py", line 620, in inner_f
    return func(**kwargs)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\sklearn.py", line 1440, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3 4 5 6 7], got [ 0  1  4  5  6  7 10 11]

--------------------------------------------------------------------------------
108 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ayoub\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\core.py", line 620, in inner_f
    return func(**kwargs)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\sklearn.py", line 1440, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3 4 5 6 7], got [ 1  3  4  5  6  7 10 11]

--------------------------------------------------------------------------------
108 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ayoub\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\core.py", line 620, in inner_f
    return func(**kwargs)
  File "C:\Users\ayoub\anaconda3\lib\site-packages\xgboost\sklearn.py", line 1440, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3 4 5 6 7 8], got [ 0  1  3  4  5  6  7 10 11]

In [ ]:
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Best Model Accuracy: {accuracy:.2f}")